#!/bin/sh

echo "Downloading and installing needed software."

apt-get update
apt-get -y install apache2 mysql-server-5.0 mysql-client-5.0 php5 php5-mysql openssh-server openssh-client build-essential

http://dl.google.com/dl/linux/direct/google-chrome-beta_current_i386.deb
dpkg -i google-chrome-beta_current_i386.deb

echo "... Done"

chmod -R 777 /pos

echo "Establish databases"

/pos/installation/ubuntu/lane_db-install

echo "compiling scanner scale daemon"

cd /pos/is4c/rs232
gcc ssd.c -o ssd

echo "... Done"

echo "Installing device drivers"

if [ /etc/init.d/ssd ]; then
  rm /etc/init.d/ssd
fi

if [ /etc/init.d/lptty ]; then
  rm /etc/init.d/lptty
fi


ln -s /pos/is4c/rs232/ssd /etc/init.d/ssd
ln -s /pos/is4c/rs232/lptty /etc/init.d/lptty

/pos/installation/ubuntu/rclocal_lane.pl

/pos/installation/ubuntu/startssd
/etc/init.d/lptty

echo "... Done"

#Configure php
/pos/installation/ubuntu/php_lane.pl
#Configure apache2
/pos/installation/ubuntu/apache_lane.pl

echo "IS4C configuration completed"
cat /pos/installation/ubuntu/is4c.header

echo "Enter to load browser and start IS4C: "
read STARTIS4C

google-chrome "localhost"
