<?php

/*
 * phpMyEdit language file
 *
 * language: german (standard)
 * encoding: iso-8859-1
 * date: 2002-07
 * authors:
 *   Christof Brandstetter <fellz@users.sourceforge.net>
 *   Gerd Xhonneux, http://xsite.xhonneux.com
 * info: http://makeashorterlink.com/?O116223C2
 */

/* $Platon: phpMyEdit/lang/PME.lang.DE.inc,v 1.14 2004-12-27 20:14:29 nepto Exp $ */

return Array(
		'Add'           =>'Hinzufügen',
		'Copy'         	=>'Kopieren',
		'Change'        =>'Ändern',
		'Delete'        =>'Löschen',
		'View'      	=>'Anzeigen',
		'Prev'          =>'Zurück',
		'Next'          =>'Weiter',
		'First'         =>'First', // untranslated
		'Last'          =>'Last',  // untranslated
		'Go to'         =>'Go to', // untranslated
		'Page'          =>'Seite',
		'Records'       =>'Datensätze',
		'Save'          =>'Speichern',
		'More'          =>'Speichern, weiteren Datensatz hinzufügen',
		'Apply'         =>'Anwenden',
		'Cancel'        =>'Abbrechen',
		'Search'		=>'Suche',
		'Hide'			=>'Verstecken',
		'Clear'			=>'Löschen',
		'Query'			=>'Abfrage',
		'Current Query'	=>'Aktuelle Abfrage',
		'Sorted By'		=>'Sortiert nach',
		'ascending'		=>'aufsteigend',
		'descending'	=>'absteigend',
		'hidden'		=>'versteckt',
		'of'			=>'von',
		'record added'  =>'Datensatz hinzugefügt',
		'record changed'=>'Datensatz geändert',
		'record deleted'=>'Datensatz gelöscht',
		'Please enter'  =>'Bitte füllen sie dieses Feld aus:',
		'months' =>	Array(
				'01'=>'Januar',
				'02'=>'Februar',
				'03'=>'März',
				'04'=>'April',
				'05'=>'Mai',
				'06'=>'Juni',
				'07'=>'Juli',
				'08'=>'August',
				'09'=>'September',
				'10'=>'Oktober',
				'11'=>'November',
				'12'=>'Dezember'),
		// phpMyEdit-report
		'Make report'			=> 'Make report',
		'Select fields'			=> 'Select fields',
		'Records per screen'	=> 'Records per screen',
		);

?>
